### ISSUE TITLE
7/2023. Database error when naming and saving new VAM activity

### ISSUE THREAD

**Issue by BM373** [BM373/moodle-mod_videoassessment#2]
Adding a new instance of VAM results in a database error.
Workaround exists. Detailed in video.

https://github.com/BM373/moodle-mod_videoassessment/assets/82206382/6861864e-9187-47f2-9376-c4b0b8270f01

**Comment by donhinkelman** [comment]
I like this project "6/2023" way of setting up the changes for VAM in 2023. I think this bug should be #2 to match the issue in github. Then subsequent issues will be #3, #4, #5, #6 for this project. How about renaming this issue as "6/2023. Database error when naming and saving new VAM activity".

**Comment by BM373** [comment]
Done.

**Comment by BM373** [comment]
The video shows Moodle version as 4.1.3.  The same error exists on updated Moodle version 4.1.4+ (Build: 20230707).
VAM version 20230428001.
